[package]
name = "transit-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arguments = "0.8.0"
bincode = "1.3.3"
chrono = "0.4.39"
geo = { version = "0.29.2", features = ["serde", "use-serde"] }
gtfs-structures = "0.42.0"
ittapi = "0.4.0"
osmpbfreader = "0.16.1"
rand = "0.8.5"
rstar = "0.12.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_with = "3.11.0"
tokio = "1.42.0"

[profile.release]
debug = true
